## Creating Multi-dimensional Arrays for Computing

Now, we will be focusing on creating multi-dimensional arrays for numerical computing. These may not be used as extensively in data science, but they are an integral part of the NumPy library. 

Let us now look at them. 

In [1]:
import numpy as np

### Creating arrays of binary numbers 0 and 1

We have some specified methods to create arrays of the binary numbers 0 and 1. These pre-defined methods create multi-dimensional arrays for us containing either 0 or 1 or both. These methods are -

1. __`zeros()`__ - This method creates an array of zeros. It takes a number, or a numerical data structure as arguments.  
2. __`ones()`__ - This method creates an array of ones. It takes arguments similar to the `zeros()` method.  
3. __`full()`__ - This method creates an array of a single number repeated to the size of the array, both being specified as arguments. This can be an array of 2s, 3s, 10s or any other number.  
4. __`eye()`__ - This method creates an identity matrix of `'n'` dimensions, where `n` is taken as a parameter. 
5. __`tile()`__ - This method creates an array by repeating the data structure defined in its arguments by a number `'n'`, which is also given as argument.

Let us now see them in action.

In [2]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.full([5,4],2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
np.tile([1,2,3,4,5,4,3,2,1,0],4)

array([1, 2, 3, 4, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 4, 3, 2, 1, 0, 1, 2,
       3, 4, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 4, 3, 2, 1, 0])

These methods are very useful for creating printing patterns. However, more often than not, we have to deal with sequences of different types in data science. For them, we have some more methods to create arrays. 

### Creating Arrays for Sequences

Now, we will be using some methods used to create arrays that follow a particular sequence. This can already be accomplished by using the `range()` function, but these methods are a step-up from the function. They are -

1. __`arange()`__ - This method creates an array of integers by defining a start, end and step value. In many ways, it is similar to the `range()` function. It takes a start value, an end value, and a step value as arguments.   
2. __`linspace()`__ - This method will create an array of numbers between two numbers, and a chunk value given, which will decide how many elements the array will have. For eg. if the chunk is 20, and the numbers are 0 and 5, then the array will contain 20 numbers between 0 and 5.
3. __`random()`__ - This function will create an array of random numbers between any two numbers, that are taken as arguments. 

Let us now see them in action.

In [7]:
np.arange(0,10,0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25,
       5.5 , 5.75, 6.  , 6.25, 6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  ,
       8.25, 8.5 , 8.75, 9.  , 9.25, 9.5 , 9.75])

In [8]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [9]:
np.random.random(20)

array([0.24892976, 0.16040531, 0.72534257, 0.8651455 , 0.31583676,
       0.34373613, 0.77078745, 0.13698691, 0.87051141, 0.53831621,
       0.39162707, 0.61714935, 0.65558715, 0.13827088, 0.26205726,
       0.42986083, 0.56794717, 0.86858147, 0.01265645, 0.66620235])

We also have another method `randint()`, that takes two values as arguments and returns a random integer between them. Let us see how it is used.

In [10]:
np.random.randint(-5,10)

9

This is how arrays are used to create specific sequences. Next, we will see how we can create arrays for special mathematical functions.

### Creating Arrays using methods for Special Mathematical Functions

Here, we will create arrays using methods that define some special mathematical functions. These include trigonometric ratios like sine,cosines,tangents, or exponential functions like power and log. It has the following methods -

1. __`power()`__ - This method is used to create an array of powers of a data structure. We can simply use the power operator (**) but this is another way to do it. 
2. __`absolute()`__ - This method is used to return an array that gives all the absolute (positive) values of each numeric element inside the array.
3. __`sin()`__ - This method is used to create an array of the sines of all the elements inside the array.
4. __`cos()`__ - This method is used to create an array of the cosines of all the elements inside the array.
5. __`log()`__ - This method is used to create an array of the logarithms of all the elements inside the array.

Let us see them in action.

In [12]:
new=np.linspace(10,25,30)
print(new)
print()
print(np.power(new,-3))

[10.         10.51724138 11.03448276 11.55172414 12.06896552 12.5862069
 13.10344828 13.62068966 14.13793103 14.65517241 15.17241379 15.68965517
 16.20689655 16.72413793 17.24137931 17.75862069 18.27586207 18.79310345
 19.31034483 19.82758621 20.34482759 20.86206897 21.37931034 21.89655172
 22.4137931  22.93103448 23.44827586 23.96551724 24.48275862 25.        ]

[1.00000000e-03 8.59596178e-04 7.44293213e-04 6.48723413e-04
 5.68839650e-04 5.01551346e-04 4.44470768e-04 3.95733400e-04
 3.53868922e-04 3.17707307e-04 2.86309636e-04 2.58916545e-04
 2.34909413e-04 2.13780839e-04 1.95112000e-04 1.78555119e-04
 1.63819798e-04 1.50662263e-04 1.38876868e-04 1.28289307e-04
 1.18751187e-04 1.10135637e-04 1.02333759e-04 9.52517181e-05
 8.88083751e-05 8.29333212e-05 7.75652605e-05 7.26506627e-05
 6.81426388e-05 6.40000000e-05]


In [13]:
x=np.full(5,128)
np.power(x,3)

array([2097152, 2097152, 2097152, 2097152, 2097152], dtype=int32)

In [15]:
negpos=np.arange(-100,100,20)

print(negpos)
print(np.absolute(negpos))

[-100  -80  -60  -40  -20    0   20   40   60   80]
[100  80  60  40  20   0  20  40  60  80]


In [18]:
trig=np.array([-1,0,1])

print(trig)
print(np.sin(trig),np.cos(trig))

[-1  0  1]
[-0.84147098  0.          0.84147098] [0.54030231 1.         0.54030231]


In [19]:
np.log([1,10,100])

array([0.        , 2.30258509, 4.60517019])

This is how we create arrays that serve multiple, specific purposes for us. Although we do have some extensive applications of arrays in linear algebra, calculus and other computing problems, our primary focus is on this aspect of arrays only.