## Manipulating NumPy Arrays

In [1]:
import numpy as np

While working over NumPy arrays, it is possible that you would have to manipulate data to obtain the desired results. NumPy arrays provide you with the feature of:
- changing the shape of an array
- combining arrays, and 
- splitting arrays................... etc.

### Stacking Arrays

When we use arithmetic operators on two arrays, it performs that operation on each element of the arrays and returns the result. However, what if we want to merge two arrays?

For this purpose, __Stacking__ occurs. It is done using the `np.hstack()` and `np.vstack()` methods. For horizontal stacking, the number of rows should be the same, while for vertical stacking, the number of columns should be the same.

Let us see some examples.

#### Horizontal Stacking

Horizontal Stacking is done, when we want to merge two arrays horizontally, i.e. the number of rows does not change. Let us see some examples.

In [2]:
arr1=np.arange(5,10)
arr2=np.arange(5)

arr1+arr2

array([ 5,  7,  9, 11, 13])

See? The operation returned an array of the sum of the arrays. Now, to merge these two arrays, we use the `hstack()` function. Let us see how it is used.

In [7]:
np.hstack((arr2,arr1))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

This is how the `hstack()` method is used to merge 2 one-dimensional arrays in python. There is one constraint for using this method - <font color="red">__The arrays passed as arguments should have equal number of rows__</font>. 

Let us see a case where this is not true. 

In [10]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2

array([0, 1, 2, 3, 4])

In [14]:
np.hstack((arr2,arr1))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

Hence, we cannot merge two arrays having different number of rows. This is proved now. Let us now move to vertical stacking of arrays.

#### Vertical Stacking

Vertical Stacking is done when we merge two arrays vertically, by their number of columns, i.e. the number of columns remains the same. Let us see some examples.

In [16]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2=np.array([[11,12,13,14,15],[16,71,18,91,110],[21,22,24,967,30],[56,31,12,41,150]])

In [17]:
arr1.shape

(2, 5)

In [18]:
arr2.shape

(4, 5)

In [21]:
np.vstack((arr1,arr2))

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  71,  18,  91, 110],
       [ 21,  22,  24, 967,  30],
       [ 56,  31,  12,  41, 150]])

See? This is how the 2-D arrays are merged. Here also, we have a constraint - <font color="red"> __We cannot merge two arrays having different number of columns__</font>. Let us see an example where this is true.

In [22]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2=np.array([[11,12,13,14],[16,71,18,91],[21,22,24,967],[56,31,12,41]])

In [23]:
arr1.shape

(2, 5)

In [24]:
arr2.shape

(4, 4)

In [26]:
np.vstack((arr1,arr2))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 4

Hence, it is proved that for stacking, we need to have the corresponding rows and columns equal, depending on the kind of stacking occurring.

### Reshaping Arrays

Reshaping arrays means that we are defining the number of rows and columns of the array. We are changing its dimensions, by specifying new dimensions. 

Reshaping is done via the `reshape()` method, which takes the array identifier, and a tuple of the rows and columns as arguments. Let us see the syntax - 

`np.reshape(identifier,(rows,cols))`

Let us see this in action.

In [29]:
arr=np.array(list(range(1,11*12+1)))
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132])

Now, let us convert this array, into an array of 11x12 dimensions, i.e. 11 rows and 12 columns. 

In [32]:
newarr=np.reshape(arr,(11,12))
newarr.shape,arr.shape

((11, 12), (132,))

See? This is how easily we reshaped an array. Now, let us see a special case. 

In [33]:
arr1=np.array(list(range(1,5*6+1)))
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
np.reshape(arr1,(5,-1))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

This is how we distributed the array into an array having 5 rows. Hence, ___we can also specify only one parameter out of rows and columns___, keeping the other one as -1.

In [37]:
np.reshape(arr1,(-1,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

See? This is such a simple way of creating multi-dimensional arrays. Let us see the dimensions for them.

In [39]:
row5,col5=np.reshape(arr1,(5,-1)),np.reshape(arr1,(-1,3))
row5.ndim,col5.ndim

(2, 2)

__Changing a 2D Array to 1D Array__

In [83]:
row1=row5.reshape(1,-1)[0]
row1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [70]:
row1.ndim

1

Hence, we created 2-D arrays by manipulating a 1-D array. This speaks volumes of the efficiency of arrays over lists. Can you think of a non-complicated way of doing this for python lists? Try to explore more !