In [9]:
import numpy as np

Now, we can use all functionalities of the NumPy library. Let us start with NumPy Arrays.

## NumPy Arrays

An __Array__ in the NumPy library is a collection of objects of the same data type. Unlike python data structures, we can have only one data type of all the elements inside an array. It can be `float`, or it can be `string` or `boolean` or `integer`. 

To create an array, we use the `array()` method defined in the NumPy library. It takes a data structure as an argument, and converts it into a NumPy array. Python is incapable of operating over the entire data stored in lists. This is where NumPy arrays come to the rescue. Let’s see how we use NumPy arrays first. 

Syntax - 	`identifier = np.array(data structure)`

Let us see some examples.

### Creating NumPy Arrays

In [16]:
a1=[1,5,4,2,7,6]
a2=5,6,7,3,2,4

type(a1),type(a2)

(list, tuple)

In [18]:
arr_a1=np.array(a1)
arr_a2=np.array(a2)

In [21]:
print(arr_a1,arr_a2)

[1 5 4 2 7 6] [5 6 7 3 2 4]


Here, you can see that the elements inside the array are separated using `whitespaces ( )` instead of `commas(,)` that happen in in-built data structures of python.

### NumPy Arrays vs Python Lists

It is important to note that <font color="red">Python lists can very well perform all the actions that a NumPy array can</font>.

It's just the fact that <font color="#000080">__NumPy arrays are faster and more convenient__ than lists when it comes to extensive computations</font> which make it extremely useful, especially when you're working with large amounts of data.

A __key advantage__ of using the NumPy arrays over Lists is that __we can operate over an entire array__, but we __cannot do that to a list__. Let us see an example.

In [26]:
print('List:',a1)
print('Array:',arr_a1)

List: [1, 5, 4, 2, 7, 6]
Array: [1 5 4 2 7 6]


Now, let us say we want to multiply the whole list by 2.5. 

__For lists__, we cannot do that directly. We have to __create a new list__, and use the __`lambda` functionality__ to do this. 

In [27]:
a1m=list(map(lambda x:x*2.5,a1))
a1m

[2.5, 12.5, 10.0, 5.0, 17.5, 15.0]

In case of __NumPy arrays__, we can simply use the __arithmetic operator `*`__ for this operation. 

In [30]:
arr_a1m=arr_a1*2.5
print(arr_a1m)

[ 2.5 12.5 10.   5.  17.5 15. ]


See? We didn't even have to use any functionality here. Simply use the arithmetic operators, and get the answer. This is where NumPy arrays hold advantage over lists. 

It is another reason __they only have elements of a single data type__. Let us see what happens when we try to convert a multi-data type list to an array.

In [33]:
li=[1,'Python',4.5,True]
li_arr=np.array(li)
print(li_arr)

['1' 'Python' '4.5' 'True']


See? Out of all the data types, it converted them into strings.

In [39]:
two=[2,2.5,False]
two_arr=np.array(two)
print(two_arr)

[2.  2.5 0. ]


Now, here we see that the boolean value is converted to a float inside the array. Hence, we come on to realize that there is a precedence of data types that will be preferred over others. The order for this is -

<span style="border:2px solid #000080; padding:1%; text-align:center; font-size:120%; font-family:cambria math; color:#000080; background-color:azure">strings > floats > integers > booleans</span>

This means that out of all the data types present in a multi-type data structure, the converted array will give preference in the above order for its data type. 

### Operations on Arrays

Now, let us see some basic operations on arrays. For this, we will create two 1-D arrays using the `range()` function and perform operations on them. 

In [50]:
arr1,arr2=np.array(range(1,10)),np.array(range(11,20))
arr1,arr2

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19]))

#### Arithmetic Operations

In [59]:
print('Sum:',arr1+arr2)
print('Difference:',arr1-arr2)
print('Product:',arr1*arr2)
print('Float Quotient:',arr2/arr1)
print('Floor Quotient:',arr2//arr1)
print('Modulus:',arr2%arr1)
print('Power:',arr2**arr1)

Sum: [12 14 16 18 20 22 24 26 28]
Difference: [-10 -10 -10 -10 -10 -10 -10 -10 -10]
Product: [ 11  24  39  56  75  96 119 144 171]
Float Quotient: [11.          6.          4.33333333  3.5         3.          2.66666667
  2.42857143  2.25        2.11111111]
Floor Quotient: [11  6  4  3  3  2  2  2  2]
Modulus: [0 0 1 2 0 4 3 2 1]
Power: [         11         144        2197       38416      759375    16777216
   410338673 -1864941312   565150579]


Hence, it is clearly visible that all the arithmetic operations are possible for numerical arrays. If the arrays were of string type, then it won't be possible since strings do not support arithmetic operators other than (+).

Now, let us look for relationship operations.

#### Relationship Operations

In [89]:
4 in arr1, 5 not in arr1

(True, False)

In [99]:
arr1 is not arr2

True

Hence, we can clearly see that we are able to perform relationship operations on the arrays. Now, let us look for logical operations.

#### Logical Operations

In [111]:
arr1<=arr2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [102]:
arr1!=arr2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [126]:
(4 in arr1)|(25 in arr2)

True

In [127]:
(4 in arr1) & (25 in arr2)

False

Therefore, we can see that we are able to perform all the logical operations on the arrays. 

Hence, we can see that __arrays are automatically comparing each element within themselves to return the output__ required by the user. This is another reason they hold advantage over lists and other data structures.

### Accessing Elements inside an Array

The elements of an array can be accessed in the same way as lists - by using indexes and slicing. This is a feature of arrays that is exactly the same as python lists and tuples. 

Let us see some examples.

In [151]:
arr1=np.array(range(1,15))
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Indexing in Arrays

We use indexing in the same way as lists - using the square brackets `[]` and specifying the index inside them. Let us see some examples for forward and reverse indexing.

In [167]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [169]:
arr1[1],arr1[3]

(2, 4)

In [171]:
arr1[-1],arr1[-3]

(14, 12)

Hence, this is how we use indexing in arrays - exactly as same as lists. Now, let us see slicing for arrays.

#### Slicing in Arrays

Slicing, just like indexing, is done in exactly the same manner as lists. We use the square brackets `[]` and the colon `(:)` for slicing. Let us see some examples.

In [172]:
arr1[2:-3]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [173]:
arr1[::-4]

array([14, 10,  6,  2])

See? These are exactly the same as lists. So, there is no need to learn slicing and indexing for arrays separately, if you know these concepts for lists.

### Some Common Methods for Arrays

There are some common methods that are used with arrays. Note that, for arrays also, we put the brackets `()` after the method name, like we do in lists. The basic syntax is -

`identifier.<method-name>()`

Let us see some common methods now.

#### The `min()`, `max()` and `mean()` Methods

The most common methods used in arrays are the maximum, minimum and the average methods. These methods used on an array can easily carry out the respective functionalities. 

In [174]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [176]:
arr1.mean(),arr1.max(),arr1.min()

(7.5, 14, 1)

#### The `sort()` Method

This method is used in arrays in just the same way as lists. It is able to sort the array in ascending order by default.

In [201]:
list1=[6,8,2,3,1,5,6,7,2,3,1,4,5]
arr_list1=np.array(list1)
arr_list1

array([6, 8, 2, 3, 1, 5, 6, 7, 2, 3, 1, 4, 5])

In [187]:
arr_list1.sort()
arr_list1

array([1, 1, 2, 2, 3, 3, 4, 5, 5, 6, 6, 7, 8])

### Filtering an Array

The functionality provided to us by the `filter()` function for lists, can be used for arrays without any function. Let us see an example for this. 

In [207]:
list1=[1,2,5,4,2,6,7,8,3,2,1,5,6,3,6,7,3,4]
list1

[1, 2, 5, 4, 2, 6, 7, 8, 3, 2, 1, 5, 6, 3, 6, 7, 3, 4]

Now, we need to create a list of all the elements greater than the average of the list. For that, we use 3 different functions - the `sum()`,the `len()` and the `filter()` functions, along with the lambda functionality. Let us see them in action. 

In [208]:
greater_than_average=list(filter(lambda x: x > sum(list1)/len(list1),list1))
greater_than_average

[5, 6, 7, 8, 5, 6, 6, 7]

By using arrays, we will simply use a `mean()` method, along with some `filter indexing` to create the array for the same. Let us see it in action.

In [209]:
list1_arr=np.array(list1)
list1_arr

array([1, 2, 5, 4, 2, 6, 7, 8, 3, 2, 1, 5, 6, 3, 6, 7, 3, 4])

In [212]:
greater_than_average_arr = list1_arr[list1_arr > list1_arr.mean()]
greater_than_average_arr

array([5, 6, 7, 8, 5, 6, 6, 7])

See? With the use of just a single method, we were able to create a __filtered array__. Such syntax is used for array filtering in NumPy. Now, we can simply typecast it into a list.

In [213]:
gta=list(greater_than_average_arr)
gta

[5, 6, 7, 8, 5, 6, 6, 7]

Hence, this is how the filter indexing can be used to created filtered arrays. These functionalities are used extensively in data science, and usually preferred over lists.