In [1]:
import numpy as np
import pandas as pd

### Q1) Consider an (8, 8) shape NumPy array. What is the index (x,y) of the 50th element?

In [8]:
np.arange(64).reshape(8,8)[6,2]

50

### Q3) What will the output of np.arange(1,16,2).reshape(4, 2) be?

In [9]:
np.arange(1,16,2).reshape(4, 2) 

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

### Q4) __Coding Console Question__ - Given a single positive odd integer 'n' greater than 2, create a NumPy array of size (n x n) with all zeros and ones such that the ones make a shape like '+'. The lines of the plus must be present in the middle row and column.

In [26]:
n=int(input())
if n%2!=0:
  arr=np.zeros((n,n),dtype=int)
  arr[n//2]=np.ones(n)
  arr[:,n//2]=np.ones(n,dtype=int)
  print(arr)
else: print('error')

5
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
